namespace ShadowMod.Native
{
    public enum CONTEXT_FLAGS : uint
    {
        CONTEXT_i386     = 0x10000,
        CONTEXT_i486     = 0x10000,   //  same as i386

        CONTEXT_CONTROL            = CONTEXT_i386 | 0x1,  // SS:SP, CS:IP, FLAGS, BP
        CONTEXT_INTEGER            = CONTEXT_i386 | 0x2,  // AX, BX, CX, DX, SI, DI
        CONTEXT_SEGMENTS           = CONTEXT_i386 | 0x4,  // DS, ES, FS, GS
        CONTEXT_FLOATING_POINT     = CONTEXT_i386 | 0x8,  // 387 state
        CONTEXT_DEBUG_REGISTERS    = CONTEXT_i386 | 0x10, // DB 0-3,6,7
        CONTEXT_EXTENDED_REGISTERS = CONTEXT_i386 | 0x20, // cpu specific extensions

        CONTEXT_FULL = CONTEXT_CONTROL | CONTEXT_INTEGER | CONTEXT_SEGMENTS,
        CONTEXT_ALL  = CONTEXT_CONTROL | CONTEXT_INTEGER | CONTEXT_SEGMENTS | CONTEXT_FLOATING_POINT | CONTEXT_DEBUG_REGISTERS | CONTEXT_EXTENDED_REGISTERS
    }
}